In [1]:
# analise de vendas por região 

import pandas as pd
import numpy as np

df_vendas = pd.read_csv("dataset_pratica_limpeza_200k.csv")
display(df_vendas)
display(df_vendas.columns)
display(df_vendas.describe())
df_analise = df_vendas.copy()

# ================================
# 1. REMOÇÃO DE DUPLICADOS
# ================================
df_analise = df_analise.drop_duplicates(subset=["id_venda"])


# ================================
# 2. TRATAMENTO DE VALORES INVÁLIDOS
# ================================
df_analise.loc[df_analise["quantidade"] <= 0, "quantidade"] = None
df_analise.loc[df_analise["preco_unitario"] <= 0, "preco_unitario"] = None

df_analise = df_analise.dropna(
    subset=["quantidade", "preco_unitario", "id_venda"]
)


# ================================
# 3. TRATAMENTO DE VARIÁVEIS CATEGÓRICAS
# ================================
df_analise["status_pedido"] = df_analise["status_pedido"].fillna("Presencial")
df_analise["categoria"] = df_analise["categoria"].fillna("Não informado")
df_analise["produto"] = df_analise["produto"].fillna("Não informado")
df_analise["nome_cliente"] = df_analise["nome_cliente"].fillna("Não informado")
df_analise["cidade"] = df_analise["cidade"].fillna("Não informado")
df_analise["estado"] = df_analise["estado"].fillna("Não informado")


df_analise["categoria"] = df_analise["categoria"].str.strip().str.title()
df_analise["produto"] = df_analise["produto"].str.strip().str.title()
df_analise["estado"] = df_analise["estado"].str.strip().str.upper()

# ================================
# 4. TRATAMENTO DE IDADE
# ================================
df_analise["idade"] = df_analise["idade"].fillna(-1)

df_analise.loc[
    (df_analise["idade"] > 100) | (df_analise["idade"] <= 0),
    "idade"
] = -1


# ================================
# 5. TRATAMENTO DE DATAS
# ================================
df_analise["data_compra"] = pd.to_datetime(
    df_analise["data_compra"],
    format="%Y-%m-%d %H:%M:%S",
    errors="coerce"
)

df_analise["data_valida"] = df_analise["data_compra"].notna()


# ================================
# 6. FEATURE ENGINEERING
# ================================
df_analise["valor_total"] = (
    df_analise["quantidade"] * df_analise["preco_unitario"]
)
df_analise["ticket_medio"] = (
    df_analise["valor_total"] / df_analise["quantidade"]
)
dic_regiao = {
'RJ': "Sudeste",
'SP': "Sudeste",
'PR': "Sul", 
'Não informado': None
,'RS': "Sul",
'MG': "Sudeste"
}
df_analise["regiao"] = df_analise["estado"].map(dic_regiao)

# ================================
# 7. VALIDAÇÃO FINAL
# ================================
display(df_analise["data_compra"].isna().sum())
display(df_analise)

# 1. ORDENAÇÃO DOS DADOS

# Ordenando por maior valor de venda e, em caso de empate, pela data mais recente
df_analise = df_analise.sort_values(
    by=["valor_total", "data_compra"],
    ascending=[False, False]
)

# Resetando o índice após ordenação
df_analise = df_analise.reset_index(drop=True)

display(df_analise)



# 2. FILTRO POR REGIÃO

# Criando DataFrames filtrados por região

df_vendas_sudeste = df_analise[
    df_analise["regiao"] == "Sudeste"
]

df_vendas_sul = df_analise[
    df_analise["regiao"] == "Sul"
]

# Registros onde a região não foi identificada (NaN)
df_vendas_desconhecido = df_analise[
    df_analise["regiao"].isna()
]


# 3. VISUALIZAÇÃO DOS RESULTADOS

display(df_vendas_sudeste)
display(df_vendas_sul)
display(df_vendas_desconhecido)

# 1. FILTRO POR PRODUTO E REGIÃO
# Vendas do Produto A na região Sudeste
df_vendas_A_sudeste = df_analise[
    (df_analise["produto"] == "Produto A") &
    (df_analise["regiao"] == "Sudeste")
]


# 2. FILTRO POR PERÍODO (ANO)
# Vendas realizadas no ano de 2024
df_vendas_2024 = df_analise[
    df_analise["data_compra"].dt.year == 2024
]

# 3. VISUALIZAÇÃO DOS RESULTADO
display(df_vendas_A_sudeste)
display(df_vendas_2024)
# ================================
# 1. RANKING DE FATURAMENTO POR ESTADO
# ================================
df_analise_estado = (
    df_analise[["estado", "valor_total"]]
    .groupby("estado")
    .sum()
    .sort_values(by="valor_total", ascending=False)
    .reset_index()
)

df_analise_estado["valor_total"] = df_analise_estado["valor_total"].map(
    lambda x: f"R$ {x:,.2f}"
)


# ================================
# 2. PRODUTOS MAIS VENDIDOS NO PR
# ================================
df_analise_PR_produtos = (
    df_analise[df_analise["estado"] == "PR"]
    .groupby("produto", as_index=False)["quantidade"]
    .sum()
    .sort_values(by="quantidade", ascending=False)
)


# ================================
# 3. ANÁLISE CRUZADA (ESTADO x PRODUTO)
# ================================
df_produto_estado = (
    df_analise[["estado", "produto", "quantidade"]]
    .groupby(["estado", "produto"])
    .sum()
)

df_estado_produto = (
    df_analise[["estado", "produto", "quantidade"]]
    .groupby(["produto", "estado"])
    .sum()
)


# ================================
# 4. VISUALIZAÇÃO
# ================================
display(df_produto_estado)
display(df_estado_produto)
display(df_analise_estado)
display(df_analise_PR_produtos)
df_pivot = df_analise.pivot_table(
    values="quantidade",
    index="estado",
    columns="produto",
    aggfunc="sum",
    fill_value=0
)

display(df_pivot)

,id_venda,cliente_id,nome_cliente,idade,cidade,estado,categoria,produto,preco_unitario,quantidade,data_compra,status_pedido
0,1,2824.0,NaN,NaN,Rio de Janeiro,RJ,Alimentos,Produto A,594.59,1.0,2022-06-14 08:28:15,NaN
1,2,NaN,Bruno,-1.0,São Paulo,RJ,Móveis,Produto C,285.09,11.0,2021-01-14 13:49:57,Cancelado
2,3,NaN,NaN,200.0,Porto Alegre,SP,Móveis,Produto A,-50.00,NaN,2022-02-26 02:31:56,NaN
3,4,NaN,Ana,NaN,São Paulo,PR,Eletrônicos,NaN,NaN,NaN,NaN,NaN
4,5,2169.0,Eduardo,NaN,Rio de Janeiro,PR,Móveis,Produto C,-50.00,18.0,2023-08-21 02:02:11,Concluído
...,...,...,...,...,...,...,...,...,...,...,...,...
199995,199996,1355.0,Eduardo,-1.0,São Paulo,NaN,Móveis,Produto A,NaN,10.0,NaN,Em transporte
199996,199997,9348.0,Eduardo,200.0,Porto Alegre,SP,Móveis,Produto B,NaN,-3.0,2020-03-01 15:54:55,Concluído
199997,199998,4396.0,Carlos,NaN,Belo Horizonte,PR,Alimentos,Produto C,-50.00,-3.0,NaN,NaN
199998,199999,NaN,NaN,-1.0,Belo Horizonte,NaN,Alimentos,Produto A,-50.00,NaN,NaN,NaN
199999,200000,1640.0,Eduardo,NaN,São Paulo,RS,Eletrônicos,Produto B,908.38,NaN,NaN,Concluído

Index(['id_venda', 'cliente_id', 'nome_cliente', 'idade', 'cidade', 'estado',
       'categoria', 'produto', 'preco_unitario', 'quantidade', 'data_compra',
       'status_pedido'],
      dtype='str')

,id_venda,cliente_id,idade,preco_unitario,quantidade
count,200000.000000,100079.000000,150180.000000,133495.000000,133508.000000
mean,100000.500000,5504.532799,82.651165,226.983385,3.792612
std,57735.171256,2599.235711,85.998828,343.318514,7.895942
min,1.000000,1000.000000,-1.000000,-50.000000,-3.000000
25%,50000.750000,3254.000000,-1.000000,-50.000000,-3.000000
50%,100000.500000,5508.000000,49.000000,-50.000000,1.000000
75%,150000.250000,7750.000000,200.000000,504.095000,11.000000
max,200000.000000,9999.000000,200.000000,999.990000,20.000000

np.int64(11317)

,id_venda,cliente_id,nome_cliente,idade,cidade,estado,categoria,produto,preco_unitario,quantidade,data_compra,status_pedido,data_valida,valor_total,ticket_medio,regiao
0,1,2824.0,Não informado,-1.0,Rio de Janeiro,RJ,Alimentos,Produto A,594.59,1.0,2022-06-14 08:28:15,Presencial,True,594.59,594.59,Sudeste
1,2,NaN,Bruno,-1.0,São Paulo,RJ,Móveis,Produto C,285.09,11.0,2021-01-14 13:49:57,Cancelado,True,3135.99,285.09,Sudeste
17,18,8811.0,Ana,79.0,Rio de Janeiro,SP,Beleza,Produto A,678.46,13.0,2022-10-05 21:04:40,Presencial,True,8819.98,678.46,Sudeste
21,22,NaN,Não informado,21.0,Não informado,PR,Eletrônicos,Produto A,13.51,9.0,NaT,Presencial,False,121.59,13.51,Sul
23,24,5088.0,Carlos,-1.0,Porto Alegre,NÃO INFORMADO,Roupas,Produto B,865.96,14.0,NaT,Presencial,False,12123.44,865.96,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199973,199974,1136.0,Não informado,79.0,São Paulo,PR,Roupas,Não Informado,998.16,15.0,2022-01-24 00:45:54,Em transporte,True,14972.40,998.16,Sul
199976,199977,NaN,Eduardo,-1.0,Belo Horizonte,RJ,Eletrônicos,Produto B,254.99,5.0,2024-09-06 23:41:53,Cancelado,True,1274.95,254.99,Sudeste
199987,199988,NaN,Daniela,-1.0,Não informado,SP,Roupas,Não Informado,836.64,2.0,NaT,Cancelado,False,1673.28,836.64,Sudeste
199991,199992,NaN,Ana,-1.0,Porto Alegre,MG,Roupas,Produto C,455.78,14.0,NaT,Em transporte,False,6380.92,455.78,Sudeste
199994,199995,NaN,Não informado,-1.0,Porto Alegre,SP,Eletrônicos,Produto A,640.74,3.0,NaT,Presencial,False,1922.22,640.74,Sudeste

,id_venda,cliente_id,nome_cliente,idade,cidade,estado,categoria,produto,preco_unitario,quantidade,data_compra,status_pedido,data_valida,valor_total,ticket_medio,regiao
0,75442,NaN,Não informado,-1.0,Belo Horizonte,SP,Roupas,Produto C,999.57,20.0,2021-04-02 01:06:44,Presencial,True,19991.40,999.57,Sudeste
1,22811,NaN,Não informado,-1.0,Rio de Janeiro,RJ,Alimentos,Produto B,999.35,20.0,2021-02-08 07:54:02,Cancelado,True,19987.00,999.35,Sudeste
2,87080,5588.0,Não informado,47.0,São Paulo,RS,Alimentos,Não Informado,995.94,20.0,2024-04-18 15:51:29,Pendente,True,19918.80,995.94,Sul
3,86744,NaN,Não informado,35.0,Belo Horizonte,PR,Roupas,Não Informado,994.64,20.0,NaT,Cancelado,False,19892.80,994.64,Sul
4,113160,1567.0,Não informado,-1.0,Belo Horizonte,SP,Alimentos,Produto C,994.59,20.0,2020-04-09 09:25:15,Presencial,True,19891.80,994.59,Sudeste
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22394,189584,8381.0,Daniela,-1.0,Rio de Janeiro,NÃO INFORMADO,Móveis,Produto A,13.66,1.0,NaT,Pendente,False,13.66,13.66,NaN
22395,172302,NaN,Bruno,-1.0,Porto Alegre,NÃO INFORMADO,Eletrônicos,Não Informado,13.62,1.0,NaT,Presencial,False,13.62,13.62,NaN
22396,188723,NaN,Eduardo,-1.0,Rio de Janeiro,PR,Móveis,Produto A,13.10,1.0,NaT,Presencial,False,13.10,13.10,Sul
22397,196988,8824.0,Daniela,-1.0,Belo Horizonte,RJ,Roupas,Não Informado,12.08,1.0,2021-08-21 01:05:54,Presencial,True,12.08,12.08,Sudeste
22398,67944,1085.0,Eduardo,-1.0,São Paulo,MG,Roupas,Produto A,10.00,1.0,NaT,Concluído,False,10.00,10.00,Sudeste

,id_venda,cliente_id,nome_cliente,idade,cidade,estado,categoria,produto,preco_unitario,quantidade,data_compra,status_pedido,data_valida,valor_total,ticket_medio,regiao
0,75442,NaN,Não informado,-1.0,Belo Horizonte,SP,Roupas,Produto C,999.57,20.0,2021-04-02 01:06:44,Presencial,True,19991.40,999.57,Sudeste
1,22811,NaN,Não informado,-1.0,Rio de Janeiro,RJ,Alimentos,Produto B,999.35,20.0,2021-02-08 07:54:02,Cancelado,True,19987.00,999.35,Sudeste
4,113160,1567.0,Não informado,-1.0,Belo Horizonte,SP,Alimentos,Produto C,994.59,20.0,2020-04-09 09:25:15,Presencial,True,19891.80,994.59,Sudeste
9,75335,2207.0,Carlos,-1.0,Rio de Janeiro,MG,Beleza,Produto C,991.73,20.0,NaT,Em transporte,False,19834.60,991.73,Sudeste
12,51616,NaN,Eduardo,-1.0,Belo Horizonte,MG,Alimentos,Não Informado,985.99,20.0,NaT,Cancelado,False,19719.80,985.99,Sudeste
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22390,3712,NaN,Não informado,-1.0,São Paulo,SP,Alimentos,Não Informado,15.32,1.0,2021-07-27 06:30:33,Concluído,True,15.32,15.32,Sudeste
22392,166809,7067.0,Daniela,68.0,Não informado,SP,Móveis,Não Informado,14.20,1.0,NaT,Em transporte,False,14.20,14.20,Sudeste
22393,137697,8853.0,Não informado,-1.0,Porto Alegre,SP,Eletrônicos,Produto B,13.94,1.0,2022-04-13 23:28:46,Cancelado,True,13.94,13.94,Sudeste
22397,196988,8824.0,Daniela,-1.0,Belo Horizonte,RJ,Roupas,Não Informado,12.08,1.0,2021-08-21 01:05:54,Presencial,True,12.08,12.08,Sudeste
22398,67944,1085.0,Eduardo,-1.0,São Paulo,MG,Roupas,Produto A,10.00,1.0,NaT,Concluído,False,10.00,10.00,Sudeste

,id_venda,cliente_id,nome_cliente,idade,cidade,estado,categoria,produto,preco_unitario,quantidade,data_compra,status_pedido,data_valida,valor_total,ticket_medio,regiao
2,87080,5588.0,Não informado,47.0,São Paulo,RS,Alimentos,Não Informado,995.94,20.0,2024-04-18 15:51:29,Pendente,True,19918.80,995.94,Sul
3,86744,NaN,Não informado,35.0,Belo Horizonte,PR,Roupas,Não Informado,994.64,20.0,NaT,Cancelado,False,19892.80,994.64,Sul
5,185054,2804.0,Daniela,-1.0,São Paulo,RS,Beleza,Produto B,994.26,20.0,2020-01-04 17:39:58,Cancelado,True,19885.20,994.26,Sul
6,128804,NaN,Não informado,-1.0,Não informado,PR,Eletrônicos,Não Informado,994.22,20.0,NaT,Presencial,False,19884.40,994.22,Sul
8,115135,NaN,Não informado,-1.0,São Paulo,RS,Alimentos,Produto C,992.41,20.0,2021-03-19 13:21:24,Presencial,True,19848.20,992.41,Sul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22383,144628,9135.0,Carlos,55.0,São Paulo,PR,Móveis,Produto C,20.76,1.0,NaT,Em transporte,False,20.76,20.76,Sul
22386,39917,NaN,Não informado,-1.0,Porto Alegre,RS,Alimentos,Produto B,17.50,1.0,NaT,Concluído,False,17.50,17.50,Sul
22387,72245,NaN,Bruno,-1.0,São Paulo,PR,Roupas,Produto B,16.72,1.0,2024-05-28 16:20:40,Pendente,True,16.72,16.72,Sul
22389,113448,NaN,Daniela,-1.0,Não informado,RS,Beleza,Produto A,16.04,1.0,NaT,Pendente,False,16.04,16.04,Sul
22396,188723,NaN,Eduardo,-1.0,Rio de Janeiro,PR,Móveis,Produto A,13.10,1.0,NaT,Presencial,False,13.10,13.10,Sul

,id_venda,cliente_id,nome_cliente,idade,cidade,estado,categoria,produto,preco_unitario,quantidade,data_compra,status_pedido,data_valida,valor_total,ticket_medio,regiao
7,185123,NaN,Daniela,-1.0,Não informado,NÃO INFORMADO,Roupas,Não Informado,992.80,20.0,NaT,Pendente,False,19856.00,992.80,NaN
10,57531,NaN,Ana,-1.0,São Paulo,NÃO INFORMADO,Alimentos,Produto C,991.47,20.0,2022-05-18 09:47:29,Presencial,True,19829.40,991.47,NaN
14,180749,8085.0,Bruno,30.0,São Paulo,NÃO INFORMADO,Alimentos,Não Informado,983.21,20.0,2021-10-01 02:34:55,Concluído,True,19664.20,983.21,NaN
18,123233,6063.0,Não informado,35.0,Belo Horizonte,NÃO INFORMADO,Eletrônicos,Produto B,978.38,20.0,2022-08-08 12:47:48,Concluído,True,19567.60,978.38,NaN
19,163020,6418.0,Carlos,-1.0,Belo Horizonte,NÃO INFORMADO,Alimentos,Produto A,978.09,20.0,NaT,Cancelado,False,19561.80,978.09,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22384,153736,NaN,Bruno,47.0,Belo Horizonte,NÃO INFORMADO,Alimentos,Produto A,19.38,1.0,2024-10-01 23:56:50,Em transporte,True,19.38,19.38,NaN
22385,83247,1034.0,Bruno,-1.0,Curitiba,NÃO INFORMADO,Eletrônicos,Produto A,18.99,1.0,NaT,Pendente,False,18.99,18.99,NaN
22391,103404,3537.0,Não informado,-1.0,Curitiba,NÃO INFORMADO,Eletrônicos,Produto A,14.77,1.0,2020-03-25 05:43:02,Presencial,True,14.77,14.77,NaN
22394,189584,8381.0,Daniela,-1.0,Rio de Janeiro,NÃO INFORMADO,Móveis,Produto A,13.66,1.0,NaT,Pendente,False,13.66,13.66,NaN
22395,172302,NaN,Bruno,-1.0,Porto Alegre,NÃO INFORMADO,Eletrônicos,Não Informado,13.62,1.0,NaT,Presencial,False,13.62,13.62,NaN

,id_venda,cliente_id,nome_cliente,idade,cidade,estado,categoria,produto,preco_unitario,quantidade,data_compra,status_pedido,data_valida,valor_total,ticket_medio,regiao
27,28301,NaN,Eduardo,51.0,São Paulo,SP,Eletrônicos,Produto A,971.34,20.0,NaT,Concluído,False,19426.80,971.34,Sudeste
30,133645,NaN,Não informado,-1.0,São Paulo,RJ,Roupas,Produto A,969.99,20.0,2025-04-21 19:45:20,Concluído,True,19399.80,969.99,Sudeste
36,152615,3312.0,Ana,21.0,Curitiba,MG,Roupas,Produto A,965.30,20.0,2021-12-31 01:37:44,Concluído,True,19306.00,965.30,Sudeste
37,106562,NaN,Carlos,33.0,Não informado,SP,Alimentos,Produto A,964.82,20.0,NaT,Presencial,False,19296.40,964.82,Sudeste
42,136307,NaN,Eduardo,-1.0,Não informado,MG,Alimentos,Produto A,961.06,20.0,NaT,Presencial,False,19221.20,961.06,Sudeste
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22362,193806,NaN,Daniela,-1.0,São Paulo,SP,Alimentos,Produto A,37.53,1.0,2024-01-26 19:36:14,Cancelado,True,37.53,37.53,Sudeste
22363,169857,8738.0,Bruno,55.0,São Paulo,SP,Roupas,Produto A,37.32,1.0,2021-10-08 01:02:46,Em transporte,True,37.32,37.32,Sudeste
22377,60135,7152.0,Daniela,-1.0,Porto Alegre,MG,Eletrônicos,Produto A,24.17,1.0,NaT,Cancelado,False,24.17,24.17,Sudeste
22388,90496,NaN,Eduardo,-1.0,Não informado,MG,Alimentos,Produto A,16.14,1.0,2020-08-26 13:29:36,Presencial,True,16.14,16.14,Sudeste
22398,67944,1085.0,Eduardo,-1.0,São Paulo,MG,Roupas,Produto A,10.00,1.0,NaT,Concluído,False,10.00,10.00,Sudeste

,id_venda,cliente_id,nome_cliente,idade,cidade,estado,categoria,produto,preco_unitario,quantidade,data_compra,status_pedido,data_valida,valor_total,ticket_medio,regiao
2,87080,5588.0,Não informado,47.0,São Paulo,RS,Alimentos,Não Informado,995.94,20.0,2024-04-18 15:51:29,Pendente,True,19918.80,995.94,Sul
11,196592,NaN,Carlos,-1.0,Não informado,PR,Eletrônicos,Produto B,989.93,20.0,2024-11-20 13:48:27,Concluído,True,19798.60,989.93,Sul
43,96081,6709.0,Ana,-1.0,Porto Alegre,RS,Móveis,Produto B,959.27,20.0,2024-12-26 16:22:13,Presencial,True,19185.40,959.27,Sul
54,181778,NaN,Carlos,-1.0,São Paulo,RJ,Alimentos,Produto A,999.35,19.0,2024-12-10 21:34:17,Cancelado,True,18987.65,999.35,Sudeste
85,102214,NaN,Não informado,-1.0,São Paulo,MG,Móveis,Produto A,937.14,20.0,2024-01-02 14:30:13,Em transporte,True,18742.80,937.14,Sudeste
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22362,193806,NaN,Daniela,-1.0,São Paulo,SP,Alimentos,Produto A,37.53,1.0,2024-01-26 19:36:14,Cancelado,True,37.53,37.53,Sudeste
22366,117335,1966.0,Carlos,-1.0,Belo Horizonte,RS,Eletrônicos,Produto C,31.87,1.0,2024-06-30 20:10:40,Cancelado,True,31.87,31.87,Sul
22374,130828,5157.0,Ana,-1.0,Porto Alegre,NÃO INFORMADO,Móveis,Produto A,26.77,1.0,2024-06-20 19:23:11,Presencial,True,26.77,26.77,NaN
22384,153736,NaN,Bruno,47.0,Belo Horizonte,NÃO INFORMADO,Alimentos,Produto A,19.38,1.0,2024-10-01 23:56:50,Em transporte,True,19.38,19.38,NaN
22387,72245,NaN,Bruno,-1.0,São Paulo,PR,Roupas,Produto B,16.72,1.0,2024-05-28 16:20:40,Pendente,True,16.72,16.72,Sul

                             quantidade
estado        produto
MG            Não Informado      9250.0
              Produto A         10077.0
              Produto B          9547.0
              Produto C          9924.0
NÃO INFORMADO Não Informado      9781.0
              Produto A          9708.0
              Produto B         10157.0
              Produto C          9846.0
PR            Não Informado      9544.0
              Produto A          9440.0
              Produto B         10154.0
              Produto C         10127.0
RJ            Não Informado      9711.0
              Produto A          9661.0
              Produto B         10043.0
              Produto C         10152.0
RS            Não Informado      8953.0
              Produto A          9843.0
              Produto B         10392.0
              Produto C         10185.0
SP            Não Informado     10131.0
              Produto A          9499.0
              Produto B          9873.0
              Produto C          9328.0

                             quantidade
produto       estado
Não Informado MG                 9250.0
              NÃO INFORMADO      9781.0
              PR                 9544.0
              RJ                 9711.0
              RS                 8953.0
              SP                10131.0
Produto A     MG                10077.0
              NÃO INFORMADO      9708.0
              PR                 9440.0
              RJ                 9661.0
              RS                 9843.0
              SP                 9499.0
Produto B     MG                 9547.0
              NÃO INFORMADO     10157.0
              PR                10154.0
              RJ                10043.0
              RS                10392.0
              SP                 9873.0
Produto C     MG                 9924.0
              NÃO INFORMADO      9846.0
              PR                10127.0
              RJ                10152.0
              RS                10185.0
              SP                 9328.0

          estado       valor_total
0             PR  R$ 20,267,664.03
1             RS  R$ 19,974,646.98
2             RJ  R$ 19,901,911.32
3  NÃO INFORMADO  R$ 19,712,358.54
4             MG  R$ 19,604,670.81
5             SP  R$ 19,544,132.35

         produto  quantidade
2      Produto B     10154.0
3      Produto C     10127.0
0  Não Informado      9544.0
1      Produto A      9440.0

produto        Não Informado  Produto A  Produto B  Produto C
estado
MG                    9250.0    10077.0     9547.0     9924.0
NÃO INFORMADO         9781.0     9708.0    10157.0     9846.0
PR                    9544.0     9440.0    10154.0    10127.0
RJ                    9711.0     9661.0    10043.0    10152.0
RS                    8953.0     9843.0    10392.0    10185.0
SP                   10131.0     9499.0     9873.0     9328.0